FROM ubuntu:16.04

LABEL maintainer Li Jiangjin(lijj@singula-point.com)

# currently, nothing to add...


# change timezone
COPY Shanghai /etc/localtime

# change locale
# for chinese input
ENV LANG C.UTF-8 
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

CMD ["bash"]

